global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: checkout
    static_configs:
      - targets: ["checkout:8000"]
  - job_name: inventory
    static_configs:
      - targets: ["inventory:8000"]

